### ISSUE TITLE
Bad interaction with diff lines in git commits

### ISSUE THREAD

**Issue by gabmontes** [primer/github-syntax-theme-generator#30]
There is some bad interaction with language-diff as reported at https://github.com/miketheman/language-diff/issues/10 when using Atom as git commit editor. The commit message containing the diff is not readable. Changing themes to Atom default ones, all works ok.

![image](https://cloud.githubusercontent.com/assets/2621975/22041173/8351acf2-dce4-11e6-9eb2-7edc11f2d9db.png)

Please advise. Thanks!

Atom@1.3.0
github-atom-light-syntax@0.3.2
language-diff@0.7.0
language-git@0.15.0

**Comment by miketheman** [comment]
There's currently a deprecation cop warning, but we cannot use the "Report Issue" button to open a GitHub issue on the appropriate repo, since the URL is too long.

<details>
https://github.com/primer/github-atom-light-syntax/issues/new?title=Deprecated%20selector%20in%20%60github-atom-light-syntax/index.less%60&body=In%20%60github-atom-light-syntax/index.less%60:%20%0A%0AStarting%20from%20Atom%20v1.13.0,%20the%20contents%20of%20%60atom-text-editor%60%20elements%20are%20no%20longer%20encapsulated%20within%20a%20shadow%20DOM%20boundary.%20This%20means%20you%20should%20stop%20using%20%60:host%60%20and%20%60::shadow%60%20pseudo-selectors,%20and%20prepend%20all%20your%20syntax%20selectors%20with%20%60syntax--%60.%20To%20prevent%20breakage%20with%20existing%20style%20sheets,%20Atom%20will%20automatically%20upgrade%20the%20following%20selectors:%0A%0A*%20%60atom-text-editor,%0A:host%60%20=%3E%20%60atom-text-editor,atom-text-editor%60%0A%0A*%20%60atom-text-editor%20.line.cursor-line,%0A:host%20.line.cursor-line%60%20=%3E%20%60atom-text-editor%20.line.cursor-line,atom-text-editor%20.line.cursor-line%60%0A%0A*%20%60atom-text-editor%20.invisible,%0A:host%20.invisible%60%20=%3E%20%60atom-text-editor%20.invisible,atom-text-editor%20.invisible%60%0A%0A*%20%60atom-text-editor%20.cursor,%0A:host%20.cursor%60%20=%3E%20%60atom-text-editor%20.cursor,atom-text-editor%20.cursor%60%0A%0A*%20%60atom-text-editor%20.selection%20.region,%0A:host%20.selection%20.region%60%20=%3E%20%60atom-text-editor%20.selection%20.region,atom-text-editor%20.selection%20.region%60%0A%0A*%20%60atom-text-editor%20.bracket-matcher%20.region,%0A:host%20.bracket-matcher%20.region%60%20=%3E%20%60atom-text-editor%20.bracket-matcher%20.region,atom-text-editor%20.bracket-matcher%20.region%60%0A%0A*%20%60atom-text-editor%20.invisible-character,%0A:host%20.invisible-character%60%20=%3E%20%60atom-text-editor%20.invisible-character,atom-text-editor%20.invisible-character%60%0A%0A*%20%60atom-text-editor%20.indent-guide,%0A:host%20.indent-guide%60%20=%3E%20%60atom-text-editor%20.indent-guide,atom-text-editor%20.indent-guide%60%0A%0A*%20%60atom-text-editor%20.wrap-guide,%0A:host%20.wrap-guide%60%20=%3E%20%60atom-text-editor%20.wrap-guide,atom-text-editor%20.wrap-guide%60%0A%0A*%20%60atom-text-editor%20.gutter,%0A:host%20.gutter%60%20=%3E%20%60atom-text-editor%20.gutter,atom-text-editor%20.gutter%60%0A%0A*%20%60atom-text-editor%20.gutter%20.line-number,%0A:host%20.gutter%20.line-number%60%20=%3E%20%60atom-text-editor%20.gutter%20.line-number,atom-text-editor%20.gutter%20.line-number%60%0A%0A*%20%60atom-text-editor%20.gutter%20.line-number.cursor-line,%0A:host%20.gutter%20.line-number.cursor-line%60%20=%3E%20%60atom-text-editor%20.gutter%20.line-number.cursor-line,atom-text-editor%20.gutter%20.line-number.cursor-line%60%0A%0A*%20%60atom-text-editor%20.gutter%20.line-number.cursor-line-no-selection,%0A:host%20.gutter%20.line-number.cursor-line-no-selection%60%20=%3E%20%60atom-text-editor%20.gutter%20.line-number.cursor-line-no-selection,atom-text-editor%20.gutter%20.line-number.cursor-line-no-selection%60%0A%0A*%20%60atom-text-editor%20.gutter%20.line-number%20.icon-right,%0A:host%20.gutter%20.line-number%20.icon-right%60%20=%3E%20%60atom-text-editor%20.gutter%20.line-number%20.icon-right,atom-text-editor%20.gutter%20.line-number%20.icon-right%60%0A%0A*%20%60atom-text-editor%20.gutter:not(.git-diff-icon)%20.line-number.git-line-removed.git-line-removed::before,%0A:host%20.gutter:not(.git-diff-icon)%20.line-number.git-line-removed.git-line-removed::before%60%20=%3E%20%60atom-text-editor%20.gutter:not(.git-diff-icon)%20.line-number.git-line-removed.git-line-removed::before,atom-text-editor%20.gutter:not(.git-diff-icon)%20.line-number.git-line-removed.git-line-removed::before%60%0A%0A*%20%60atom-text-editor%20.gutter:not(.git-diff-icon)%20.line-number.git-line-removed::after,%0A:host%20.gutter:not(.git-diff-icon)%20.line-number.git-line-removed::after%60%20=%3E%20%60atom-text-editor%20.gutter:not(.git-diff-icon)%20.line-number.git-line-removed::after,atom-text-editor%20.gutter:not(.git-diff-icon)%20.line-number.git-line-removed::after%60%0A%0A*%20%60atom-text-editor%20.gutter%20.line-number.folded,%0A:host%20.gutter%20.line-number.folded,%0Aatom-text-editor%20.gutter%20.line-number:after,%0A:host%20.gutter%20.line-number:after,%0Aatom-text-editor%20.fold-marker:after,%0A:host%20.fold-marker:after%60%20=%3E%20%60atom-text-editor%20.gutter%20.line-number.folded,atom-text-editor%20.gutter%20.line-number.folded,%0Aatom-text-editor%20.gutter%20.line-number:after,atom-text-editor%20.gutter%20.line-number:after,%0Aatom-text-editor%20.fold-marker:after,atom-text-editor%20.fold-marker:after%60%0A%0A*%20%60atom-text-editor%20.search-results%20.marker%20.region,%0A:host%20.search-results%20.marker%20.region%60%20=%3E%20%60atom-text-editor%20.search-results%20.syntax--marker%20.region,atom-text-editor%20.search-results%20.syntax--marker%20.region%60%0A%0A*%20%60atom-text-editor%20.search-results%20.marker.current-result%20.region,%0A:host%20.search-results%20.marker.current-result%20.region%60%20=%3E%20%60atom-text-editor%20.search-results%20.syntax--marker.current-result%20.region,atom-text-editor%20.search-results%20.syntax--marker.current-result%20.region%60%0A%0A*%20%60.comment,%0A.punctuation.definition.comment,%0A.string.comment%60%20=%3E%20%60.syntax--comment,%0A.syntax--punctuation.syntax--definition.syntax--comment,%0A.syntax--string.syntax--comment%60%0A%0A*%20%60.constant,%0A.entity.name.constant,%0A.variable.other.constant,%0A.variable.language%60%20=%3E%20%60.syntax--constant,%0A.syntax--entity.syntax--name.syntax--constant,%0A.syntax--variable.syntax--other.syntax--constant,%0A.syntax--variable.syntax--language%60%0A%0A*%20%60.entity,%0A.entity.name%60%20=%3E%20%60.syntax--entity,%0A.syntax--entity.syntax--name%60%0A%0A*%20%60.variable.parameter.function%60%20=%3E%20%60.syntax--variable.syntax--parameter.syntax--function%60%0A%0A*%20%60.entity.name.tag%60%20=%3E%20%60.syntax--entity.syntax--name.syntax--tag%60%0A%0A*%20%60.keyword%60%20=%3E%20%60.syntax--keyword%60%0A%0A*%20%60.storage,%0A.storage.type%60%20=%3E%20%60.syntax--storage,%0A.syntax--storage.syntax--type%60%0A%0A*%20%60.storage.modifier.package,%0A.storage.modifier.import,%0A.storage.type.java%60%20=%3E%20%60.syntax--storage.syntax--modifier.syntax--package,%0A.syntax--storage.syntax--modifier.syntax--import,%0A.syntax--storage.syntax--type.syntax--java%60%0A%0A*%20%60.string,%0A.punctuation.definition.string,%0A.string%20.punctuation.section.embedded%20.source%60%20=%3E%20%60.syntax--string,%0A.syntax--punctuation.syntax--definition.syntax--string,%0A.syntax--string%20.syntax--punctuation.syntax--section.syntax--embedded%20.syntax--source%60%0A%0A*%20%60.support%60%20=%3E%20%60.syntax--support%60%0A%0A*%20%60.meta.property-name%60%20=%3E%20%60.syntax--meta.syntax--property-name%60%0A%0A*%20%60.variable%60%20=%3E%20%60.syntax--variable%60%0A%0A*%20%60.variable.other%60%20=%3E%20%60.syntax--variable.syntax--other%60%0A%0A*%20%60.invalid.broken%60%20=%3E%20%60.syntax--invalid.syntax--broken%60%0A%0A*%20%60.invalid.deprecated%60%20=%3E%20%60.syntax--invalid.syntax--deprecated%60%0A%0A*%20%60.invalid.illegal%60%20=%3E%20%60.syntax--invalid.syntax--illegal%60%0A%0A*%20%60.invalid.unimplemented%60%20=%3E%20%60.syntax--invalid.syntax--unimplemented%60%0A%0A*%20%60.message.error%60%20=%3E%20%60.syntax--message.syntax--error%60%0A%0A*%20%60.string%20.source%60%20=%3E%20%60.syntax--string%20.syntax--source%60%0A%0A*%20%60.string%20.variable%60%20=%3E%20%60.syntax--string%20.syntax--variable%60%0A%0A*%20%60.source.regexp,%0A.string.regexp%60%20=%3E%20%60.syntax--source.syntax--regexp,%0A.syntax--string.syntax--regexp%60%0A%0A*%20%60.string.regexp.character-class,%0A.string.regexp%20.constant.character.escape,%0A.string.regexp%20.source.ruby.embedded,%0A.string.regexp%20.string.regexp.arbitrary-repitition%60%20=%3E%20%60.syntax--string.syntax--regexp.syntax--character-class,%0A.syntax--string.syntax--regexp%20.syntax--constant.syntax--character.syntax--escape,%0A.syntax--string.syntax--regexp%20.syntax--source.syntax--ruby.syntax--embedded,%0A.syntax--string.syntax--regexp%20.syntax--string.syntax--regexp.syntax--arbitrary-repitition%60%0A%0A*%20%60.string.regexp%20.constant.character.escape%60%20=%3E%20%60.syntax--string.syntax--regexp%20.syntax--constant.syntax--character.syntax--escape%60%0A%0A*%20%60.support.constant%60%20=%3E%20%60.syntax--support.syntax--constant%60%0A%0A*%20%60.support.variable%60%20=%3E%20%60.syntax--support.syntax--variable%60%0A%0A*%20%60.meta.module-reference%60%20=%3E%20%60.syntax--meta.syntax--module-reference%60%0A%0A*%20%60.markup.list%60%20=%3E%20%60.syntax--markup.syntax--list%60%0A%0A*%20%60.markup.heading,%0A.markup.heading%20.entity.name%60%20=%3E%20%60.syntax--markup.syntax--heading,%0A.syntax--markup.syntax--heading%20.syntax--entity.syntax--name%60%0A%0A*%20%60.markup.quote%60%20=%3E%20%60.syntax--markup.syntax--quote%60%0A%0A*%20%60.markup.italic%60%20=%3E%20%60.syntax--markup.syntax--italic%60%0A%0A*%20%60.markup.bold%60%20=%3E%20%60.syntax--markup.syntax--bold%60%0A%0A*%20%60.markup.raw%60%20=%3E%20%60.syntax--markup.syntax--raw%60%0A%0A*%20%60.markup.deleted,%0A.meta.diff.header.from-file,%0A.punctuation.definition.deleted%60%20=%3E%20%60.syntax--markup.syntax--deleted,%0A.syntax--meta.syntax--diff.syntax--header.syntax--from-file,%0A.syntax--punctuation.syntax--definition.syntax--deleted%60%0A%0A*%20%60.markup.inserted,%0A.meta.diff.header.to-file,%0A.punctuation.definition.inserted%60%20=%3E%20%60.syntax--markup.syntax--inserted,%0A.syntax--meta.syntax--diff.syntax--header.syntax--to-file,%0A.syntax--punctuation.syntax--definition.syntax--inserted%60%0A%0A*%20%60.markup.changed,%0A.punctuation.definition.changed%60%20=%3E%20%60.syntax--markup.syntax--changed,%0A.syntax--punctuation.syntax--definition.syntax--changed%60%0A%0A*%20%60.markup.ignored,%0A.markup.untracked%60%20=%3E%20%60.syntax--markup.syntax--ignored,%0A.syntax--markup.untracked%60%0A%0A*%20%60.meta.diff.range%60%20=%3E%20%60.syntax--meta.syntax--diff.syntax--range%60%0A%0A*%20%60.meta.diff.header%60%20=%3E%20%60.syntax--meta.syntax--diff.syntax--header%60%0A%0A*%20%60.meta.separator%60%20=%3E%20%60.syntax--meta.syntax--separator%60%0A%0A*%20%60.meta.output%60%20=%3E%20%60.syntax--meta.syntax--output%60%0A%0A*%20%60.brackethighlighter.tag,%0A.brackethighlighter.curly,%0A.brackethighlighter.round,%0A.brackethighlighter.square,%0A.brackethighlighter.angle,%0A.brackethighlighter.quote%60%20=%3E%20%60.brackethighlighter.syntax--tag,%0A.brackethighlighter.syntax--curly,%0A.brackethighlighter.syntax--round,%0A.brackethighlighter.syntax--square,%0A.brackethighlighter.syntax--angle,%0A.brackethighlighter.syntax--quote%60%0A%0A*%20%60.sublimelinter.mark.error%60%20=%3E%20%60.sublimelinter.syntax--mark.syntax--error%60%0A%0A*%20%60.sublimelinter.mark.warning%60%20=%3E%20%60.sublimelinter.syntax--mark.syntax--warning%60%0A%0A*%20%60.constant.other.reference.link,%0A.string.other.link%60%20=%3E%20%60.syntax--constant.syntax--other.syntax--reference.syntax--link,%0A.syntax--string.syntax--other.syntax--link%60%0A%0AAutomatic%20translation%20of%20selectors%20will%20be%20removed%20in%20a%20few%20release%20cycles%20to%20minimize%20startup%20time.%20Please,%20make%20sure%20to%20upgrade%20the%20above%20selectors%20as%20soon%20as%20possible.

</details>

Results in `414 Request-URI Too Large`

The actual message is:

> Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

I had previously made the corrections in https://github.com/miketheman/language-diff/commit/cee2a9f80e7522ea3605a40e64a10c4671edb23d so you might look to there for some help.

**Comment by broccolini** [comment]
Thank you for letting us know about the issue! Someone from the atom team is helping me out with a fix.

**Comment by sharifzadesina** [comment]
Theme is useless with this bug, when we can have this fixed @broccolini?

**Comment by jonrohan** [comment]
Sorry for the long reply on this, I've been on medical leave until now. Will be fixed in the next release
